project_id = "mbuajcicosojebakdtsn"

[functions.get-for-you-feed]
verify_jwt = false

[functions.get-recommended-feed]
verify_jwt = false

[functions.smart-search]
verify_jwt = false

[functions.process-video]
verify_jwt = false

[functions.admin-stats]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.admin-videos]
verify_jwt = true

[functions.admin-delete-video]
verify_jwt = true
